# Generated by Django 6.0 on 2025-12-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
    ]
